query SingleMangaQuery($slug: String!) {
    single_man_by_pk(id: $slug) {
        id
        title
        alternativeName
        artist
        author
        coverImg
        genres
        chapters
        description
        slug
        status
        rating
        dates
    }
}
