query SingleMangaQuery($slug: String!) {
    singleMang( where: { slug: { _eq: $slug } } ) {
        id
        title
        alternativeName
        artist
        author
        coverImage
        genres
        chapters
        description
        slug
        status
        rating
        dates
    }
}