import { Inter } from 'next/font/google';
import './globals.css';
import '../index.scss';
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import { Analytics } from '@vercel/analytics/react';
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Manga Story - Best Comics, High Quality Comics & Manga',
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
